#pragma config(Hubs, S1, HTMotor, none, none, none)
#pragma config(Motor, mtr_S1_C1_1, dc1, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_2, motorE, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		//each stick controls a motor
		getJoystickSettings(joystick);

		if(joystick.joy1_y1 < 20 && joystick.joy1_y1>-20)
		{
			motor[dc1] = 0;
		}
		else
		{
			motor[dc1] = joystick.joy1_y1;
		}
	}
}
